apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world
  labels:
    {{- include "edp-tekton.labels" . | nindent 4 }}
spec:
  params:
  - name: BASE_IMAGE
    type: string
    default: "alpine"
    description: "The base Docker image to use for the task"
  - name: username
    type: string
    description: "The username to personalize the task's output"
  workspaces:
    - description: A workspace that contains fetched git repo.
      name: source
  steps:
    - name: hello-world
      image: $(params.BASE_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        echo "Hello $(params.username), the repository contains the following files:"
        ls -al
